apiVersion: apps/v1
kind: Deployment
metadata:
        name: demo
        labels:
                app: demo
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: demo
        template:
                metadata:
                        labels: 
                                app: demo
                spec:
                        containers:
                                - name: demo
                                  image: go-demo:latest
                                  ports:
                                  - containerPort: 8080
                                  imagePullPolicy: IfNotPresent 
                                  resources:
                                    requests:
                                      memory: "10Mi"
                                      cpu: "100m"
                                    limits:
                                      memory: "20Mi"
                                      cpu: "200m"
                                  livenessProbe:
                                    httpGet:
                                      path: /
                                      port: 8080
                                    initialDelaySeconds: 3
                                    periodSeconds: 3
                                  readinessProbe:
                                    httpGet:
                                      path: /
                                      port: 8080
                                    initialDelaySeconds: 3
                                    periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
        name: demo
        labels:
                app: demo
spec:
        ports:
        - port: 9999
          protocol: TCP
          targetPort: 8080 
        selector:
          app: demo
        type: NodePort
